# Generated by Django 4.1.1 on 2022-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='page',
            field=models.CharField(default='waiting', max_length=100),
            preserve_default=False,
        ),
    ]
